# Generated by Django 3.0.7 on 2020-06-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20200620_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='user_follows',
        ),
    ]
