# Generated by Django 3.0.7 on 2020-06-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200622_1215'),
        ('userprofiles', '0004_auto_20200620_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shared_posts',
            field=models.ManyToManyField(blank=True, related_name='users_who_shared', to='posts.Post'),
        ),
    ]
