# Generated by Django 3.0.7 on 2020-06-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200622_1215'),
        ('userprofiles', '0005_userprofile_shared_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='posts.Post'),
        ),
    ]
