version: '3'
services:
  app:
    image: registry.gitlab.propulsion-home.ch/joseph-gill/week-7/day-3:latest
    env_file:
      - ./env/dev.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: "python manage.py runserver 0:8000"
    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./env/dev.env
#    volumes:
#      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

#  nginx:
#    image: nginx:latest
#    ports:
#      - 8080:80
#    volumes:
#      - ./nginx:/etc/nginx/conf.d

volumes:
  postgres_db:

