# Generated by Django 3.0.7 on 2020-06-22 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('requested', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friends_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
