# Generated by Django 3.0.7 on 2020-06-22 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendrequests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='requested',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requested',
            field=models.ManyToManyField(related_name='friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requester',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requester',
            field=models.ManyToManyField(related_name='friends_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
