# Generated by Django 3.0.7 on 2020-06-22 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registrationprofiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=registrationprofiles.models.code_generator, help_text='Random code user for registration and password reset', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
